const CACHE_NAME = 'sr-app-shell-v8';
const APP_SHELL = [
  './',
  './index.html',
  './style.css',
  './app.js',
  './supabase.js',
  './push-config.js',
  './manifest.webmanifest',
  './assets/sr-logo.svg',
  './assets/sr-icon-192.png',
  './assets/sr-icon-512.png',
];

async function cacheAppShell() {
  const cache = await caches.open(CACHE_NAME);
  // Do not fail the entire Service Worker install if an optional asset is missing.
  await Promise.all(APP_SHELL.map(async (url) => {
    try {
      const response = await fetch(url, { cache: 'no-cache' });
      if (response.ok) await cache.put(url, response);
    } catch {
      // The network may be temporarily unavailable during installation.
    }
  }));
}

self.addEventListener('install', (event) => {
  event.waitUntil(cacheAppShell());
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(
      keys
        .filter((key) => key.startsWith('sr-app-shell-') && key !== CACHE_NAME)
        .map((key) => caches.delete(key)),
    );
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put('./index.html', copy));
          return response;
        })
        .catch(() => caches.match('./index.html')),
    );
    return;
  }

  if (['style', 'script', 'image', 'font'].includes(request.destination)) {
    event.respondWith(
      caches.match(request).then((cached) => {
        const update = fetch(request)
          .then((response) => {
            if (response.ok) {
              caches.open(CACHE_NAME).then((cache) => cache.put(request, response.clone()));
            }
            return response;
          })
          .catch(() => cached || Response.error());

        return cached || update;
      }),
    );
    return;
  }

  event.respondWith(
    fetch(request)
      .then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(request, copy));
        }
        return response;
      })
      .catch(() => caches.match(request)),
  );
});

/*
 * SR Web Push
 * Compatible with the payload generated by:
 * supabase/functions/send-push-notification/index.ts
 */
self.addEventListener('push', (event) => {
  event.waitUntil((async () => {
    let payload = {};

    try {
      payload = event.data ? event.data.json() : {};
    } catch {
      payload = { body: event.data ? event.data.text() : '' };
    }

    const title = payload.title || 'SR · Sin Restricciones';
    const body = payload.body || 'Tienes una nueva notificación.';
    const notificationId = payload.notificationId || '';
    const postId = payload.postId || '';
    const actorId = payload.actorId || '';

    const tag = payload.tag || `sr-notification-${notificationId || Date.now()}`;

    const options = {
      body,
      icon: payload.icon || './assets/sr-icon-192.png',
      badge: payload.badge || './assets/sr-icon-192.png',
      tag,
      renotify: true,
      requireInteraction: false,
      timestamp: Date.now(),
      data: {
        url: payload.url || './',
        notificationId,
        postId,
        actorId,
      },
      actions: [
        { action: 'open', title: 'Abrir SR' },
        { action: 'close', title: 'Cerrar' },
      ],
    };

    await self.registration.showNotification(title, options);
  })());
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  event.waitUntil((async () => {
    const data = event.notification.data || {};

    if (event.action === 'close') return;

    const targetUrl = new URL(data.url || './', self.location.origin).href;
    const clientsList = await self.clients.matchAll({
      type: 'window',
      includeUncontrolled: true,
    });

    // Prefer an already-open SR tab so the user does not get duplicates.
    for (const client of clientsList) {
      if (!client.url.startsWith(self.location.origin)) continue;

      if ('focus' in client) {
        await client.focus();
      }

      client.postMessage({
        type: 'SR_NOTIFICATION_CLICK',
        notificationId: data.notificationId || '',
        postId: data.postId || '',
        actorId: data.actorId || '',
      });

      return;
    }

    // No SR window is open: launch it and let the app open the correct content.
    const client = await self.clients.openWindow(targetUrl);
    if (client) {
      // Give the page a moment to initialize before sending the click payload.
      setTimeout(() => {
        client.postMessage({
          type: 'SR_NOTIFICATION_CLICK',
          notificationId: data.notificationId || '',
          postId: data.postId || '',
          actorId: data.actorId || '',
        });
      }, 500);
    }
  })());
});

self.addEventListener('notificationclose', (event) => {
  // Reserved for future analytics. No data is sent from the Service Worker.
  event.waitUntil(Promise.resolve());
});
